/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AutoTraderRouteImport } from './routes/auto-trader'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as CompteDerivRouteImport } from './routes/compte-deriv'
import { Route as GestionRisqueRouteImport } from './routes/gestion-risque'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as IaTradingRouteImport } from './routes/ia-trading'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MarchesRouteImport } from './routes/marches'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as SignauxRouteImport } from './routes/signaux'
import { Route as StrategiesRouteImport } from './routes/strategies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoTraderRoute = AutoTraderRouteImport.update({
  id: '/auto-trader',
  path: '/auto-trader',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteDerivRoute = CompteDerivRouteImport.update({
  id: '/compte-deriv',
  path: '/compte-deriv',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRisqueRoute = GestionRisqueRouteImport.update({
  id: '/gestion-risque',
  path: '/gestion-risque',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const IaTradingRoute = IaTradingRouteImport.update({
  id: '/ia-trading',
  path: '/ia-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchesRoute = MarchesRouteImport.update({
  id: '/marches',
  path: '/marches',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignauxRoute = SignauxRouteImport.update({
  id: '/signaux',
  path: '/signaux',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/auto-trader': typeof AutoTraderRoute
  '/backtest': typeof BacktestRoute
  '/compte-deriv': typeof CompteDerivRoute
  '/gestion-risque': typeof GestionRisqueRoute
  '/historique': typeof HistoriqueRoute
  '/ia-trading': typeof IaTradingRoute
  '/journal': typeof JournalRoute
  '/marches': typeof MarchesRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/portfolio': typeof PortfolioRoute
  '/positions': typeof PositionsRoute
  '/signaux': typeof SignauxRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/auto-trader': typeof AutoTraderRoute
  '/backtest': typeof BacktestRoute
  '/compte-deriv': typeof CompteDerivRoute
  '/gestion-risque': typeof GestionRisqueRoute
  '/historique': typeof HistoriqueRoute
  '/ia-trading': typeof IaTradingRoute
  '/journal': typeof JournalRoute
  '/marches': typeof MarchesRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/portfolio': typeof PortfolioRoute
  '/positions': typeof PositionsRoute
  '/signaux': typeof SignauxRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administration': typeof AdministrationRoute
  '/auto-trader': typeof AutoTraderRoute
  '/backtest': typeof BacktestRoute
  '/compte-deriv': typeof CompteDerivRoute
  '/gestion-risque': typeof GestionRisqueRoute
  '/historique': typeof HistoriqueRoute
  '/ia-trading': typeof IaTradingRoute
  '/journal': typeof JournalRoute
  '/marches': typeof MarchesRoute
  '/messagerie': typeof MessagerieRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
  '/portfolio': typeof PortfolioRoute
  '/positions': typeof PositionsRoute
  '/signaux': typeof SignauxRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administration'
    | '/auto-trader'
    | '/backtest'
    | '/compte-deriv'
    | '/gestion-risque'
    | '/historique'
    | '/ia-trading'
    | '/journal'
    | '/marches'
    | '/messagerie'
    | '/notes'
    | '/parametres'
    | '/portfolio'
    | '/positions'
    | '/signaux'
    | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/administration'
    | '/auto-trader'
    | '/backtest'
    | '/compte-deriv'
    | '/gestion-risque'
    | '/historique'
    | '/ia-trading'
    | '/journal'
    | '/marches'
    | '/messagerie'
    | '/notes'
    | '/parametres'
    | '/portfolio'
    | '/positions'
    | '/signaux'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administration'
    | '/auto-trader'
    | '/backtest'
    | '/compte-deriv'
    | '/gestion-risque'
    | '/historique'
    | '/ia-trading'
    | '/journal'
    | '/marches'
    | '/messagerie'
    | '/notes'
    | '/parametres'
    | '/portfolio'
    | '/positions'
    | '/signaux'
    | '/strategies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdministrationRoute: typeof AdministrationRoute
  AutoTraderRoute: typeof AutoTraderRoute
  BacktestRoute: typeof BacktestRoute
  CompteDerivRoute: typeof CompteDerivRoute
  GestionRisqueRoute: typeof GestionRisqueRoute
  HistoriqueRoute: typeof HistoriqueRoute
  IaTradingRoute: typeof IaTradingRoute
  JournalRoute: typeof JournalRoute
  MarchesRoute: typeof MarchesRoute
  MessagerieRoute: typeof MessagerieRoute
  NotesRoute: typeof NotesRoute
  ParametresRoute: typeof ParametresRoute
  PortfolioRoute: typeof PortfolioRoute
  PositionsRoute: typeof PositionsRoute
  SignauxRoute: typeof SignauxRoute
  StrategiesRoute: typeof StrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-trader': {
      id: '/auto-trader'
      path: '/auto-trader'
      fullPath: '/auto-trader'
      preLoaderRoute: typeof AutoTraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte-deriv': {
      id: '/compte-deriv'
      path: '/compte-deriv'
      fullPath: '/compte-deriv'
      preLoaderRoute: typeof CompteDerivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion-risque': {
      id: '/gestion-risque'
      path: '/gestion-risque'
      fullPath: '/gestion-risque'
      preLoaderRoute: typeof GestionRisqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-trading': {
      id: '/ia-trading'
      path: '/ia-trading'
      fullPath: '/ia-trading'
      preLoaderRoute: typeof IaTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marches': {
      id: '/marches'
      path: '/marches'
      fullPath: '/marches'
      preLoaderRoute: typeof MarchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signaux': {
      id: '/signaux'
      path: '/signaux'
      fullPath: '/signaux'
      preLoaderRoute: typeof SignauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdministrationRoute: AdministrationRoute,
  AutoTraderRoute: AutoTraderRoute,
  BacktestRoute: BacktestRoute,
  CompteDerivRoute: CompteDerivRoute,
  GestionRisqueRoute: GestionRisqueRoute,
  HistoriqueRoute: HistoriqueRoute,
  IaTradingRoute: IaTradingRoute,
  JournalRoute: JournalRoute,
  MarchesRoute: MarchesRoute,
  MessagerieRoute: MessagerieRoute,
  NotesRoute: NotesRoute,
  ParametresRoute: ParametresRoute,
  PortfolioRoute: PortfolioRoute,
  PositionsRoute: PositionsRoute,
  SignauxRoute: SignauxRoute,
  StrategiesRoute: StrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
